### ISSUE TITLE
Desktop file wrongly list the app as ConsoleOnly

### ISSUE THREAD

**Issue by hosiet** [edisionnano/QDiskInfo#18]
Currently the .desktop file lists the app as `ConsoleOnly`. Accrding to XDG Menu Spec at https://specifications.freedesktop.org/menu-spec/latest/additional-category-registry.html :

```
ConsoleOnly | Application that only works inside a terminal (text-based or command line application)
```

Your App obviously does not fall in this category.

Please drop this category from the desktop file. Thanks!

**Comment by edisionnano** [comment]
Nice catch
