### ISSUE TITLE
Health status percentage larger than 100%. Is that expected?

### ISSUE THREAD

**Issue by hosiet** [edisionnano/QDiskInfo#19]
Please see the screenshot below:

![image](https://github.com/user-attachments/assets/c8b68f6f-8cbf-413f-bcdb-e0e8796b0e60)

This is the Qt6 version compiled using https://github.com/edisionnano/QDiskInfo/commit/0232c8f1838467ebf6e853a752157ca43af4025b on Debian Sid/Unstable. The Health Status is at 253%. Is this expected?

**Comment by hosiet** [comment]
The output of `smartctl --all /dev/sda` and `smartctl -x --all /dev/sda`:

[smartctl_1.txt](https://github.com/user-attachments/files/16627500/smartctl_1.txt)


[smartctl_x.txt](https://github.com/user-attachments/files/16627501/smartctl_x.txt)

**Comment by edisionnano** [comment]
Can you test the latest commit please?

**Comment by hosiet** [comment]
With the latest commit at https://github.com/edisionnano/QDiskInfo/commit/da88224810b8ea273b21ba024ba6332a7cc617aa , There's no improvement on my side.

**Comment by edisionnano** [comment]
> With the latest commit at [da88224](https://github.com/edisionnano/QDiskInfo/commit/da88224810b8ea273b21ba024ba6332a7cc617aa) , There's no improvement on my side.

Send me the json using sudo smartctl -a -j /dev/sda > sda.json

**Comment by hosiet** [comment]
[sda.json](https://github.com/user-attachments/files/16652820/sda.json)

**Comment by edisionnano** [comment]
Thank you, fixed!
