### ISSUE TITLE
Availability in Debian

### ISSUE THREAD

**Issue by hosiet** [edisionnano/QDiskInfo#21]
I have packaged qdiskinfo in Debian, and you can track its packaging condition in the long term at https://tracker.debian.org/pkg/qdiskinfo . This also means that qdiskinfo will be available in Debian 13, Ubuntu 24.10 and later Ubuntu-based releases.

For package cross-distro availability, you may also refer to https://repology.org/project/qdiskinfo/packages .

**Comment by edisionnano** [comment]
Thank you, that's great to hear! Version 0.3 should come out soon btw.
