### ISSUE TITLE
Arrow icons missing

### ISSUE THREAD

**Issue by JaakkoHintsala** [edisionnano/QDiskInfo#22]
Hello, I just installed qdiskinfo from the aur and noticed that the arrow Icons are missing like so:
![kuva](https://github.com/user-attachments/assets/804e8967-861f-4db4-828d-3e5b1b11a13d)
Perhaps there's a dependency missing from the aur package?
https://aur.archlinux.org/packages/qdiskinfo

**Comment by edisionnano** [comment]
Assuming that this is a QT6 build, you can try replacing the icon names in the UI to arrow-left and arrow-right.
Here's a binary if you want to try and tell me if it fixes that issue
[QDiskInfo.zip](https://github.com/user-attachments/files/16678632/QDiskInfo.zip)

**Comment by JaakkoHintsala** [comment]
Thanks for the fast reply.

I am running HyprLand on CachyOS right now. 
That binary is also missing the arrows for me. 
qt6ct was not installed, but installing it didn't help.

Here are all the Qt6 packages I have installed: 
LANG=C sudo pacman -Ss qt6 | grep installed | grep extra/
extra/kvantum 1.1.2-1 [installed: 1.1.2-1.1]
extra/polkit-qt6 0.200.0-1 [installed]
extra/qt6-5compat 6.7.2-1 (qt6) [installed: 6.7.2-1.1]
extra/qt6-base 6.7.2-1 (qt6) [installed: 6.7.2-1.1]
extra/qt6-declarative 6.7.2-1 (qt6) [installed: 6.7.2-1.1]
extra/qt6-imageformats 6.7.2-1 (qt6) [installed: 6.7.2-1.1]
extra/qt6-shadertools 6.7.2-1 (qt6) [installed: 6.7.2-1.1]
extra/qt6-svg 6.7.2-1 (qt6) [installed: 6.7.2-1.1]
extra/qt6-tools 6.7.2-2 (qt6) [installed: 6.7.2-2.1]
extra/qt6-translations 6.7.2-1 (qt6) [installed]
extra/qt6-wayland 6.7.2-4 (qt6) [installed: 6.7.2-4.1]
extra/qt6ct 0.9-9 [installed: 0.9-9.1]

And here are the packages I don't have:
LANG=C sudo pacman -Ss qt6 | grep -v installed | grep extra/
extra/appstream-qt 1.0.3-1
extra/deepin-qt6integration 6.0.12-1 (deepin)
extra/deepin-qt6platform-plugins 6.0.12-1 (deepin)
extra/doublecmd-qt6 1.1.17-1
extra/fcitx-qt6 1.2.7-27 (fcitx-im)
extra/fcitx5-qt 5.1.6-4 (fcitx5-im)
extra/futuresql 0.1.1-3
extra/kdsoap-qt6 2.2.0-1
extra/lazarus-qt6 3.4-1
extra/libfm-qt 2.0.2-3
extra/libqaccessibilityclient-qt6 0.6.0-1
extra/libqtxdg 4.0.0-3
extra/packagekit-qt6 1.1.2-1
extra/phonon-qt6 4.12.0-4
extra/phonon-qt6-vlc 0.12.0-2
extra/plasma5support 6.1.4-1 (plasma)
extra/poppler-qt6 24.08.0-1
extra/pyside6 6.7.2-3
extra/python-pyqt6 6.7.1-1 (pyqt6)
extra/python-pyqt6-3d 6.7.0-2 (pyqt6)
extra/python-pyqt6-charts 6.7.0-2 (pyqt6)
extra/python-pyqt6-datavisualization 6.7.0-2 (pyqt6)
extra/python-pyqt6-networkauth 6.7.0-2 (pyqt6)
extra/python-pyqt6-sip 13.8.0-1
extra/python-pyqt6-webengine 6.7.0-2 (pyqt6)
extra/python-qscintilla-qt6 2.14.1-3
extra/qca-qt6 2.3.9-2
extra/qcoro-qt6 0.10.0-1
extra/qscintilla-qt6 2.14.1-3
extra/qt6-3d 6.7.2-1 (qt6)
extra/qt6-charts 6.7.2-1 (qt6)
extra/qt6-connectivity 6.7.2-1 (qt6)
extra/qt6-datavis3d 6.7.2-1 (qt6)
extra/qt6-doc 6.7.2-1 (qt6)
extra/qt6-examples 6.7.2-1 (qt6)
extra/qt6-graphs 6.7.2-1 (qt6)
extra/qt6-grpc 6.7.2-2 (qt6)
extra/qt6-httpserver 6.7.2-1 (qt6)
extra/qt6-languageserver 6.7.2-1 (qt6)
extra/qt6-location 6.7.2-1 (qt6)
extra/qt6-lottie 6.7.2-1 (qt6)
extra/qt6-multimedia 6.7.2-1 (qt6)
extra/qt6-multimedia-ffmpeg 6.7.2-1
extra/qt6-multimedia-gstreamer 6.7.2-1
extra/qt6-networkauth 6.7.2-1 (qt6)
extra/qt6-positioning 6.7.2-1 (qt6)
extra/qt6-quick3d 6.7.2-1 (qt6)
extra/qt6-quick3dphysics 6.7.2-1 (qt6)
extra/qt6-quickeffectmaker 6.7.2-1 (qt6)
extra/qt6-quicktimeline 6.7.2-1 (qt6)
extra/qt6-remoteobjects 6.7.2-1 (qt6)
extra/qt6-scxml 6.7.2-1 (qt6)
extra/qt6-sensors 6.7.2-1 (qt6)
extra/qt6-serialbus 6.7.2-1 (qt6)
extra/qt6-serialport 6.7.2-1 (qt6)
extra/qt6-speech 6.7.2-1 (qt6)
extra/qt6-virtualkeyboard 6.7.2-1 (qt6)
extra/qt6-webchannel 6.7.2-1 (qt6)
extra/qt6-webengine 6.7.2-2 (qt6)
extra/qt6-websockets 6.7.2-1 (qt6)
extra/qt6-webview 6.7.2-1 (qt6)
extra/qt6-xcb-private-headers 6.7.2-1
extra/qt6pas 6.2.7-2
extra/qtkeychain-qt6 0.14.3-1
extra/qtpbfimageplugin-qt6 3.1-2
extra/quazip-qt6 1.4-1
extra/qxlsx-qt6 1.4.9-1
extra/qxmpp-qt6 1.8.0-1

**Comment by edisionnano** [comment]
Using qt6ct try setting a different icon theme, the icons QDiskInfo is using (minus the eye) follow the [Standard Icon Names](https://specifications.freedesktop.org/icon-naming-spec/latest/#names)

**Comment by JaakkoHintsala** [comment]
pacman -Q|grep icon-theme
adwaita-icon-theme 46.2-1
adwaita-icon-theme-legacy 46.2-1
hicolor-icon-theme 0.18-1

I got it to work now. I am not sure exactly what fixed it but here's what I did:

Added these environment variables
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
per the readme here https://github.com/trialuser02/qt6ct

Tried a bunch of different themes etc in qt6ct.

![kuva](https://github.com/user-attachments/assets/37b593ff-7aee-433c-b3be-9c0a6d8a9da5)

**Comment by edisionnano** [comment]
I added some instructions on the readme, `QT_QPA_PLATFORM=wayland` is probably not needed since QDiskInfo will run in Wayland mode by default
