### ISSUE TITLE
How to fix the: The imported target "Qt6::lprodump" references the file       "/usr/lib/qt6/libexec/lprodump"    but this file does not exist.  Possible reasons include Error

### ISSUE THREAD

**Issue by Kr666you** [edisionnano/QDiskInfo#25]
Hello. I had an issue with cmake compiling this but found a fix so i want to share the fix:

The imported target "Qt6::lconvert" references the file

     "/usr/lib/qt6/bin/lconvert"

  but this file does not exist.  Possible reasons include:

sudo apt -y install qt6-l10n-tools

The imported target "Qt6::lprodump" references the file

     "/usr/lib/qt6/libexec/lprodump"

  but this file does not exist.  Possible reasons include:

sudo apt -y install qt6-tools-dev-tools

**Comment by edisionnano** [comment]
What distro is that?
