### ISSUE TITLE
Crowding project suspended

### ISSUE THREAD

**Issue by yura04** [edisionnano/QDiskInfo#26]
When I try to edit Ukrainian or Russian translation I see window saying that translation is currently suspended asking me to contact the project owner.
![Imagepipe_73](https://github.com/user-attachments/assets/49f5d15c-2905-4770-8ea4-2426136d4f5e)

**Comment by edisionnano** [comment]
Indeed, thanks for the heads up. Apparently I need to apply for an open source license which I did and now I'm waiting for a response

**Comment by edisionnano** [comment]
It was approved, please try again

**Comment by yura04** [comment]
Translation works. Thanks
